name: basil
description: A linear build system for Dart projects, designed to be lightweight and extensible.
version: 1.0.1
repository: https://www.github.com/tytydraco/basil

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  ansicolor: ^2.0.1
  async: ^2.9.0
  logging: ^1.0.2
  process_run: ^0.12.3+2
  yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
