name: basil
description: A linear build system for Dart projects, designed to be lightweight and extensible.
version: 1.0.13
repository: https://www.github.com/tytydraco/basil

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  ansicolor: ^2.0.1
  args: ^2.3.1
  async: ^2.9.0
  io: ^1.0.3
  yaml: ^3.1.1

dev_dependencies:
  test: ^1.21.4
  very_good_analysis: ^3.0.1

executables:
  basil: main
